CREATE TABLE [dbo].[JobDetails](
	[JobDetailID] [int] IDENTITY(1,1) NOT NULL,
	[JobID] [int] NOT NULL,
	[ServiceTypeID] [int] NOT NULL,
	[Amount] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[JobDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JobDetails]  WITH CHECK ADD FOREIGN KEY([JobID])
REFERENCES [dbo].[Jobs] ([JobID])
GO

ALTER TABLE [dbo].[JobDetails]  WITH CHECK ADD FOREIGN KEY([ServiceTypeID])
REFERENCES [dbo].[ServiceTypes] ([ServiceTypeID])
GO

