CREATE TABLE [dbo].[Zipcode](
	[ZipId] [int] IDENTITY(1,1) NOT NULL,
	[CityID] [int] NOT NULL,
	[Zipcode] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ZipId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Zipcode]  WITH CHECK ADD FOREIGN KEY([CityID])
REFERENCES [dbo].[Cities] ([CityID])
GO
